regitratura/bolnicaapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^doctor/(?P<doctor_id>\d+)/contact$',views.ReceptionView, name='contact'),

    ]

regitratura/regitratura/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from bolnicaapp.views import DoctorList, ReceptionView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', DoctorList.as_view(), name='start'),
    url(r'^doctor/(?P<doctor_id>\d+)/$',ReceptionView.as_view(), name='reception'),
    url(r'^', include('bolnicaapp.urls', namespace='bolnicaapp')),



]

regitratura/bolnicaapp/models.py
from django.db import models

# Create your models here.

class Doctor (models.Model):
    name=models.CharField(verbose_name='ФИО врача', max_length = 200 )
    specialization=models.CharField(verbose_name='Специальность',max_length=200)
    info=models.TextField(verbose_name='Информация о враче')

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        verbose_name_plural = "Врачи"
        verbose_name = "Врач"


class Reception(models.Model):
    date = models.DateField(verbose_name='Дата приема ')
    time=models.TimeField(verbose_name='Время приема ')
    patient_name=models.CharField(verbose_name='ФИО пациента', max_length=200)
    patient_info=models.TextField(verbose_name='Информация о пациенте ')
    doctor=models.ForeignKey( Doctor, verbose_name='Лечащий врач ',)

    def __str__(self):
        return 'Прием № %s' % self.id

    class Meta:
        verbose_name_plural = "Приемы"
        verbose_name = "Прием"

regitratura/bolnicaapp/forms.py
# coding: utf-8
from django import forms
from .models import Doctor, Reception
from django.contrib.admin import widgets
import datetime

class ReceptionForm(forms.ModelForm):
    class Meta:
        model = Reception
        fields = ['date','time','patient_name','patient_info']

    def __init__(self, *args, **kwargs):
        super(ReceptionForm, self).__init__(*args, **kwargs)

        self.fields['patient_info'].widget = forms.Textarea(attrs={'cols': 60, 'rows': 8})
        self.fields['patient_info'].label = 'Что вас беспокоит'

regitratura/bolnicaapp/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .models import Doctor, Reception
from .forms import ReceptionForm
from datetime import datetime, date, time
from django.template import RequestContext

class DoctorList(ListView):
    model = Doctor
    template_name='start.html'
    context_object_name = 'doctors'

class ReceptionView(FormView):
    form_class = ReceptionForm
    template_name = 'reception.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.kwargs = None

    def form_valid(self, form):
        fcd = form.cleaned_data
        curr_doctor=Doctor.objects.get(id= self.kwargs['doctor_id'])
        response_dict={"form":form,
                       "doctor":curr_doctor,
                       "curr_date":fcd['date'],
                       "curr_time":fcd['time']}
        d = fcd['date']
        d1 = datetime.isoweekday(d)
        print(d1)
        t = fcd['time']
        t1 = time(9, 00)
        t2 = time(17, 00)
        # условие для предотвращения записи на один и тот же день,на то же время
        #  или выходной день у данного врача
        if Reception.objects.filter(date=fcd['date'],time=fcd['time'],doctor=curr_doctor).count()==0 and 1<=d1<=5 and t1<=t<=t2:


            Reception.objects.create(date=fcd['date'],time=fcd['time'],
                                     patient_name=fcd['patient_name'],
                                     patient_info=fcd['patient_info'],
                                     doctor=curr_doctor)
            response_dict["norm"] = "Вы записаны на прием"
            return render_to_response('reception.html', response_dict,)
        else:
            response_dict["message"]="Это время уже занято,или вы пытаетесь записаться в не рабочее время или выходной день." \
                                     " Пожалуйста выберите другое время или дату"
            return render_to_response('reception.html',response_dict,
                          )

    def get_context_data(self, **kwargs):
        context = super(ReceptionView, self).get_context_data(**kwargs)
        context['doctor']=Doctor.objects.get(id= self.kwargs['doctor_id'])
        return context

regitratura/bolnicaapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Виджет Bootstrap datetimepicker</title>
    <script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>

    {% block meta %}
      <meta name="description" content="Областная центральная клиническая больница">
      <meta name="keywords" content="Областная центральная клиническая больница" />
    {% endblock %}

    <title>
      {% block title %}
        Областная центральная клиническая больница
      {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'custom_css/custom.css' %}">
    {% block css %} {% endblock %}
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li  role="presentation" class="active"><a style="margin: 15px;" href="/">Главная</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Областная центральная клиническая больница</h3>
      </div>

      {% block content %}
      {% endblock content %}


    </div> <!-- /container -->
    <script src="{% static 'js/bootstrap.js' %}" ></script>


    <script type="text/javascript">
    $(function () {
      $('#datetimepicker1').datetimepicker({language: 'ru',minuteStepping:10,defaultDate:"09.01.2015",daysOfWeekDisabled:[0,6]});
      $('#datetimepicker2').datetimepicker({language: 'ru'});
    });
  </script>
    {% block js %}
    <script type="text/javascript">
    $(function () {
      $('#datetimepicker1').datetimepicker({language: 'ru',minuteStepping:10,defaultDate:"09.01.2015",daysOfWeekDisabled:[0,6]});
      $('#datetimepicker2').datetimepicker({language: 'ru'});
    });
  </script>
    {% endblock %}

  </body>
</html>

regitratura/bolnicaapp/templates/reception.html
{% extends "index.html" %}
{% load static %}
<title>
    {% block title %}
      {{ block.super }},{{doctor.name|safe}}, запись на прием
    {% endblock %}
  </title>

{% block content %}
    <h3>{{doctor.name|safe}}</h3>
    <p>{{doctor.specialization|safe}}</p>
    <p>{{doctor.info|safe}}</p>

    {% if norm %}
      <div align="center">
        <h3>{{norm}}<br>
            на {{curr_date}} {{curr_time}}
        </h3>
      </div>
    {%endif%}

      {%if message %}
        <div align="center">
          <h3>{{message}}</h3>
        </div>
      {%endif%}

    <br><br>

    <div align="center">
         <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title">Форма записи</h2>
  </div>
  <div class="panel-body">
<div class="well well-lg">
    <h3></h3>
      <form action="" class="form-inline" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group" align="left">
          <table class="table table-borderless">
            <tr>
            <label align="left" for="inputDate">Выберите дату:   </label>
            <input align="left" type="date" name="date" required id="id_date" class="form-control" value="">

              <br><br></tr>

            <tr><td>
                <div class="form-group">
            <label for="inputTime">Выберите время:</label>
                 <td><input type="text" name="time" required class="form-control" id="id_time" list="time" >
                    <datalist id="time">
                      <option value=09:00:00>
                      <option value=10:00:00>
                      <option value=11:00:00>
                      <option value=12:00:00>
                      <option value=13:00:00>
                      <option value=14:00:00>
                      <option value=15:00:00>
                      <option value=16:00:00>
                      <option value=17:00:00>
                    </datalist>
                <br><br></td></tr>



            <tr><th> {{form.patient_name.label}}</th><td>{{form.patient_name}}{{form.patient_name.errors}}<br><br></td></tr>
            <tr><th>{{form.patient_info.label}}</th><td>{{form.patient_info}}{{form.patient_info.errors}}<br><br></td></tr>
          </table>

            <div style="padding-left:20%;"><button id="submit" class="btn btn-success">Запись</button></div>


      </form>
    </div>
      </div>
</div>
</div>

  {% endblock content %}

regitratura/bolnicaapp/templates/start.html
{% extends "index.html" %}

  <title>
    {% block title %}
      {{ block.super }},{{doctor.name|safe}}
    {% endblock %}
  </title>

  {% block content %}
      <div class="jumbotron">
        <p class="lead">
         Институт неотложной и восстановительной хирургии им. В.К.Гусака. Расположена по адресу:
            Донецк, Ленинский проспект,47.

        </p>
        <p>Время работы поликлиники: пн - пт с 9:00 до 18:00.</p>
      </div>
        <div class="container">
      <div align="left">
          <h2>Наши врачи:</h2> </div>
        </div>
      <div class="row marketing">

        {% for doctor in doctors %}
          <div class="col-lg-6">
            {%if forloop.counter0|divisibleby:"2" == True %}
                  <h4>{{doctor.name|safe}}</h4>
                  <p>{{doctor.specialization|safe}}</p>
                  <p>{{doctor.info|safe}}</p>
                  <p> <a  class="btn btn-primary"
                       href="{% url 'reception' doctor_id=doctor.id %}">Записаться на прием</a>
                  </p>
            {% endif %}
          </div>

          <div class="col-lg-6">
            {%if forloop.counter0|divisibleby:"2" == False %}
                  <h4>{{doctor.name|safe}}</h4>
                  <p>{{doctor.specialization|safe}}</p>
                  <p>{{doctor.info|safe}}</p>
                  <p> <a class="btn btn-primary"
                       href="{% url 'reception' doctor_id=doctor.id %}">Записаться на прием</a>
                  </p>
            {% endif %}
          </div>


            {% comment %}
          <div class="col-lg-6">

                  <h4>{{doctor.name|safe}}</h4>
                  <p>{{doctor.specialization|safe}}</p>
                  <p>{{doctor.info|safe}}</p>
                  <p> <a class="btn btn-primary"
                       href="{% url 'reception' doctor_id=doctor.id %}">Записаться на прием</a>
                  </p>
          </div>
            {% endif %}

      {% endcomment %}
        {% endfor %}
      </div>
  {% endblock content %}